(()=>{
const M=G2Model,S=M.state,$=id=>document.getElementById(id);let selectedChar=null,itemsCatalog=[];
const toast=(m,ms=2600)=>{let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),ms)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dirty(){S.dirty=true;$('dirtyStatus').textContent='変更あり';$('exportBtn').disabled=false;}
function selectOptions(map,val,blank='—'){const sv=val===null||val===undefined?'':String(val),m=map||{};let a=[`<option value="" ${sv===''?'selected':''}>${blank}</option>`];if(sv!==''&&!Object.prototype.hasOwnProperty.call(m,sv))a.push(`<option value="${esc(sv)}" selected>内部ID ${esc(sv)}（未同定・現在値を保持）</option>`);for(const [k,v] of Object.entries(m))a.push(`<option value="${esc(k)}" ${sv===String(k)?'selected':''}>${esc(v)} [${esc(k)}]</option>`);return a.join('');}
async function loadDefinitions(){try{
  const [c,t,coverage]=await Promise.all([
    fetch('data/catalog.json').then(r=>{if(!r.ok)throw Error('catalog.json');return r.json()}),
    fetch('data/items.tsv').then(r=>{if(!r.ok)throw Error('items.tsv');return r.text()}),
    fetch('data/item_coverage.json').then(r=>r.ok?r.json():null).catch(()=>null)
  ]);
  const lines=t.trim().split(/\r?\n/),headers=lines.shift().split('\t');
  itemsCatalog=lines.map(line=>{const cols=line.split('\t'),o={};headers.forEach((h,i)=>o[h]=cols[i]??'');o.category_id=Number(o.category_id);return o;})
    .filter(x=>/^\d{4}$/.test(x.base_id)&&Number.isInteger(x.category_id)&&x.status!=='unresolved'&&x.status!=='blocked');
  S.catalog=c;c.items=Object.fromEntries(itemsCatalog.map(x=>[x.base_id,x]));
  const unresolved=coverage?.unresolved_total??coverage?.unresolved?.length??null;
  $('startupNotice').className='notice ok';
  $('startupNotice').textContent=`定義読込済み：安全に追加可能 ${itemsCatalog.length}件 / 職業 ${Object.keys(c.jobs).length}件 / 種族 ${Object.keys(c.races).length}件${unresolved!==null?` / ID調査中 ${unresolved}件`:''}`;
  fillStaticSelects();
}catch(e){console.error(e);$('startupNotice').className='notice error';$('startupNotice').textContent='データ定義の読込に失敗しました: '+e.message;}}
function fillStaticSelects(){const c=S.catalog;if(!c)return;
  $('itemCategory').innerHTML='<option value="">全カテゴリ</option>'+Object.entries(c.categories).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('');
  $('addBase').innerHTML=itemsCatalog.map(x=>`<option value="${x.base_id}" data-cat="${x.category_id}">${esc(x.name)} [${x.base_id}]</option>`).join('');
  $('addCategory').innerHTML=Object.entries(c.categories).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('');
  $('addCategory').disabled=true;
  $('addTitle').innerHTML=Object.entries(c.normal_titles).map(([k,v])=>`<option value="${k}" ${k==='0003'?'selected':''}>${esc(v)}</option>`).join('');
  $('addUltra').innerHTML='<option value="0000">なし</option>'+Object.entries(c.ultra_titles).map(([k,v])=>`<option value="${k}">${esc(v)} [${k}]</option>`).join('');
  syncAddItemPreview();
}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')})}
async function locateSave(file){if(typeof JSZip==='undefined')throw Error('ZIPライブラリを読み込めませんでした。通信制限またはCDN障害の可能性があります');const raw=await file.arrayBuffer(),outer=await JSZip.loadAsync(raw),names=Object.keys(outer.files);const direct=names.find(n=>n==='tmp2'||n.endsWith('/tmp2'));if(direct){return{container:'direct',zip:outer,tmp2Name:direct,tmp3Name:names.find(n=>n==='tmp3'||n.endsWith('/tmp3'))||'tmp3',outerZip:null,innerName:null}}for(const n of names){if(!/\.zip$/i.test(n))continue;try{const bytes=await outer.file(n)?.async('uint8array');if(!bytes)continue;const inner=await JSZip.loadAsync(bytes),ins=Object.keys(inner.files),t2=ins.find(x=>x==='tmp2'||x.endsWith('/tmp2'));if(t2)return{container:'nested',zip:inner,tmp2Name:t2,tmp3Name:ins.find(x=>x==='tmp3'||x.endsWith('/tmp3'))||'tmp3',outerZip:outer,innerName:n};}catch{}}throw Error('ZIP内にtmp2が見つかりません');}
async function openFile(file){try{const loc=await locateSave(file);const tmp2=new Uint8Array(await loc.zip.file(loc.tmp2Name).async('uint8array'));const tmp3=loc.zip.file(loc.tmp3Name)?(await loc.zip.file(loc.tmp3Name).async('string')).trim():'';Object.assign(S,{zip:loc.zip,tmp2,originalTmp3:tmp3,outer:G2Keyed.KeyedArchive.fromBytes(tmp2),dirty:false,sourceName:file.name,location:loc});M.loadEntries();M.loadCharacters();M.loadInventory();selectedChar=S.characters[0]||null;$('fileStatus').textContent='読込: '+file.name;$('saveMeta').textContent=`tmp2 ${tmp2.length.toLocaleString()} bytes / tmp3 ${tmp3.length||0}桁`;$('dirtyStatus').textContent='変更なし';$('exportBtn').disabled=false;$('cloneCharBtn').disabled=!selectedChar;$('addItemBtn').disabled=false;$('validateBtn').disabled=false;renderAll();toast(`読込完了：冒険者 ${S.characters.length}人 / 倉庫 ${S.inventory.length}種`);}catch(e){console.error(e);toast('読込失敗: '+e.message,5000);$('startupNotice').className='notice error';$('startupNotice').textContent='読込エラー: '+e.message;}}
function renderSummary(){if(!S.outer){$('summary').innerHTML='';return}const x=M.summary();$('summary').innerHTML=[['内部項目',x.entries],['冒険者',x.characters],['倉庫種類',x.inventory],['GP',Number(x.gp||0).toLocaleString()],['ラビット',x.rabbit??'—']].map(([a,b])=>`<div class="stat-card"><small>${a}</small><b>${esc(b)}</b></div>`).join('');}
function traitIds(c){let p1='',p2='';for(const code of M.specialCodes(c)){let b=Number(code.slice(0,4));if(b>=8901&&b<=8918)p1=String(b);if(b>=8807&&b<=8821)p2=String(b)}return{p1,p2};}
function charBuild(c){const d=c.data,ca=S.catalog||{};return `${ca.races?.[d._lineage]||'種族'+d._lineage} / ${ca.jobs?.[d._job]||'職'+d._job}${d._subjob?` ← ${ca.jobs?.[d._subjob]||d._subjob}`:''}`;}
function renderCharacters(){const box=$('charList');if(!S.characters.length){box.innerHTML='<div class="notice">冒険者を検出できません。</div>';return}box.innerHTML=S.characters.map((c,i)=>`<button class="char-row ${selectedChar===c?'active':''}" data-ci="${i}"><b>${esc(c.data._title||'(無名)')}</b><span>Lv.${esc(c.data._lv)}　${esc(charBuild(c))}　#${esc(c.data._createID)}</span></button>`).join('');box.querySelectorAll('[data-ci]').forEach(b=>b.onclick=()=>{selectedChar=S.characters[+b.dataset.ci];renderCharacters();renderCharEditor()});renderCharEditor();}
function renderCharEditor(){const e=$('charEditor');if(!selectedChar){e.className='editor-card empty';e.textContent='冒険者を選択してください。';return}e.className='editor-card';const d=selectedChar.data,c=S.catalog||{},tr=traitIds(selectedChar);const fields=[['_title','名前','text'],['_lv','Lv','number'],['_hp','HP（保存値）','number'],['_p_str','力','number'],['_p_int','知恵','number'],['_p_men','精神','number'],['_p_vit','体力','number'],['_p_agi','敏捷','number'],['_p_luk','運','number']];e.innerHTML=`<h2>${esc(d._title)} <small>#${esc(d._createID)}</small></h2><div class="form-grid">${fields.map(([k,l,t])=>`<div class="field"><label>${l}</label><input class="game-input" data-cfield="${k}" type="${t}" value="${esc(d[k]??'')}"></div>`).join('')}<div class="field"><label>種族</label><select class="game-input" data-cfield="_lineage">${selectOptions(c.races,d._lineage)}</select></div><div class="field"><label>現職</label><select class="game-input" data-cfield="_job">${selectOptions(c.jobs,d._job)}</select></div><div class="field"><label>前職</label><select class="game-input" data-cfield="_subjob">${selectOptions(c.jobs,d._subjob,'なし')}</select></div><div class="field"><label>個性1</label><select id="trait1" class="game-input">${selectOptions(c.personality1,tr.p1,'なし')}</select></div><div class="field"><label>個性2</label><select id="trait2" class="game-input">${selectOptions(c.personality2,tr.p2,'なし')}</select></div><div class="field"><label>装備数</label><input class="game-input" disabled value="${Array.isArray(d._items)?d._items.length:0}"></div></div><div class="editor-actions"><button id="deleteCharBtn" class="game-button danger">冒険者を削除</button></div>`;
e.querySelectorAll('[data-cfield]').forEach(inp=>inp.onchange=()=>{try{let k=inp.dataset.cfield,v=inp.value;if(inp.type==='number'||['_lineage','_job','_subjob'].includes(k)){v=v===''?0:Number(v);if(!Number.isSafeInteger(v))throw Error('整数として安全な範囲で指定してください');if(k==='_lv'&&v<0)throw Error('Lvは0以上で指定してください');}M.setCharacterField(selectedChar,k,v);dirty();renderSummary();renderCharacters();toast(`${k} を変更しました`);}catch(err){toast('変更拒否: '+err.message,4200);renderCharEditor();}});$('trait1').onchange=$('trait2').onchange=()=>{M.setTraits(selectedChar,$('trait1').value||null,$('trait2').value||null);dirty();renderCharacters();toast('個性を変更しました')};$('deleteCharBtn').onclick=deleteSelectedCharacter;}
function cloneSelectedCharacter(){if(!selectedChar)return;try{selectedChar=M.cloneCharacter(selectedChar);dirty();renderAll();toast(`複製しました：createID ${selectedChar.data._createID}`);}catch(e){console.error(e);toast('複製失敗: '+e.message,4500)}}
function deleteSelectedCharacter(){if(!selectedChar||!confirm(`${selectedChar.data._title} を削除します。判別できる装備は倉庫へ戻し、現在のパーティ参照を解除します。`))return;try{const info=M.deleteCharacter(selectedChar);dirty();selectedChar=S.characters[0]||null;renderAll();if(info.skipped.length)toast(`削除しました。分類未確定の装備 ${info.skipped.length}件は倉庫へ自動返却していません`,5200);else toast(`削除しました。装備 ${info.returned.length}件を倉庫へ返却しました`);}catch(e){console.error(e);toast('削除失敗: '+e.message,4500)}}
function renderItems(){const q=$('itemSearch').value.trim().toLowerCase(),cat=$('itemCategory').value;const rows=S.inventory.filter(r=>(!cat||String(r.category)===cat)&&(!q||M.itemName(r.code).toLowerCase().includes(q)||r.code.includes(q)));$('itemRows').innerHTML=rows.slice(0,1000).map((r,i)=>`<tr><td>${esc(M.itemName(r.code))}</td><td><code>${esc(r.code)}</code></td><td>${esc(S.catalog?.categories?.[r.category]||r.category)}</td><td><input class="game-input qty" type="number" min="0" value="${r.quantity}" data-inv="${S.inventory.indexOf(r)}"></td><td><button class="game-button danger" data-delitem="${S.inventory.indexOf(r)}">削除</button></td></tr>`).join('');document.querySelectorAll('[data-inv]').forEach(i=>i.onchange=()=>{let r=S.inventory[+i.dataset.inv],n=Number(i.value);if(!Number.isFinite(n)||n<0)return;M.setInventory(r,n);dirty();renderItems();renderSummary();toast('個数を変更しました')});document.querySelectorAll('[data-delitem]').forEach(b=>b.onclick=()=>{let r=S.inventory[+b.dataset.delitem];M.setInventory(r,0);dirty();renderItems();renderSummary();toast('倉庫から削除しました')});}
function syncAddItemPreview(){if(!$('addBase'))return;const base=$('addBase').value,opt=$('addBase').selectedOptions[0],def=S.catalog?.items?.[base];const cat=def?.category_id??Number(opt?.dataset.cat);if(Number.isInteger(Number(cat)))$('addCategory').value=String(cat);$('addCodePreview').textContent=(base||'0000')+($('addTitle').value||'0003')+($('addUltra').value||'0000');}
function addItem(){const base=$('addBase').value,def=S.catalog?.items?.[base];if(!def||def.status==='unresolved'||def.status==='blocked')throw Error('内部IDとカテゴリが確認済みのアイテムだけ追加できます');const cat=Number(def.category_id),code=base+($('addTitle').value||'0003')+($('addUltra').value||'0000'),q=Number($('addQuantity').value);if(!Number.isSafeInteger(q)||q<1)throw Error('個数は1以上の整数で指定してください');if(!S.entries.has(`items${cat}`))throw Error(`保存データにカテゴリ items${cat} がありません`);const ex=S.inventory.find(r=>r.category===cat&&r.code===code);if(ex)M.setInventory(ex,ex.quantity+q);else M.addInventory(cat,code,q);dirty();renderItems();renderSummary();toast(`${def.name} を追加しました`);}
function renderResources(){const defs=S.catalog?.resource_fields||[];$('resourceForm').innerHTML=defs.filter(x=>S.entries.has(x.key)).map(x=>`<div class="resource-card"><b>${esc(x.label)}</b><label>${esc(x.key)}${x.note?`<small>${esc(x.note)}</small>`:''}</label><input class="game-input" data-resource="${esc(x.key)}" type="number" step="${x.type==='integer'?'1':'any'}" ${x.min!==undefined?`min="${x.min}"`:''} ${x.max!==undefined?`max="${x.max}"`:''} value="${esc(M.get(x.key))}"></div>`).join('');document.querySelectorAll('[data-resource]').forEach(i=>i.onchange=()=>{try{const def=S.catalog.resource_fields.find(x=>x.key===i.dataset.resource);let v=Number(i.value);if(!Number.isFinite(v))throw Error('数値が不正です');if(def?.type==='integer'){v=Math.trunc(v);if(!Number.isSafeInteger(v))throw Error('安全な整数範囲を超えています');}if(def?.min!==undefined&&v<def.min)throw Error(`最小値は ${def.min} です`);if(def?.max!==undefined&&v>def.max)throw Error(`最大値は ${def.max} です`);M.setScalar(i.dataset.resource,v);dirty();renderSummary();toast(`${i.dataset.resource} を変更しました`);}catch(err){toast('変更拒否: '+err.message,4200);renderResources();}})}
function renderEntries(){if(!S.outer)return;const q=$('entrySearch').value.toLowerCase();let keys=[...S.entries.keys()].filter(k=>k.toLowerCase().includes(q)).sort();$('entryList').innerHTML=keys.map(k=>`<button class="entry-button" data-entry="${esc(k)}"><b>${esc(k)}</b> <small>${esc(typeof M.get(k))}</small></button>`).join('');document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>showEntry(b.dataset.entry));}
function safe(v){if(v instanceof Uint8Array)return`<data ${v.length} bytes>`;if(v instanceof Date)return v.toISOString();if(typeof v==='bigint')return v.toString();return v;}
function showEntry(k){let v=M.get(k),scalar=['string','number','boolean'].includes(typeof v);$('entryEditor').innerHTML=`<h2>${esc(k)}</h2><div class="code-preview">type: ${esc(typeof v)}</div>${scalar?`<label>値<input id="entryValue" class="game-input" value="${esc(v)}"></label><button id="entrySave" class="game-button">変更</button>`:`<pre style="white-space:pre-wrap;word-break:break-word">${esc(JSON.stringify(v,(a,b)=>safe(b),2).slice(0,30000))}</pre>`}`;if(scalar)$('entrySave').onclick=()=>{let nv=$('entryValue').value;if(typeof v==='number')nv=Number(nv);if(typeof v==='boolean')nv=/^(true|1|on)$/i.test(nv);M.setScalar(k,nv);dirty();showEntry(k);renderSummary();toast(`${k} を変更しました`)}}
function restoreParsedState(outer,selectedId){S.outer=outer;M.loadEntries();M.loadCharacters();M.loadInventory();selectedChar=S.characters.find(c=>String(c.data._createID)===String(selectedId))||S.characters[0]||null;}
function validate(){if(!S.outer){const r={ok:false,errors:['セーブ未読込'],warnings:[]};$('validation').className='notice error';$('validation').textContent='ERROR — セーブ未読込';return r;}const selectedId=selectedChar?.data?._createID,originalOuter=S.outer;let result;try{const pre=M.validateCurrent();if(!pre.ok)throw Error(pre.errors.slice(0,12).join(' / '));const bytes=M.flush(),round=G2Keyed.KeyedArchive.fromBytes(bytes);S.outer=round;M.loadEntries();M.loadCharacters();M.loadInventory();const post=M.validateCurrent();if(!post.ok)throw Error(post.errors.slice(0,12).join(' / '));const x=M.summary(),warnings=[...new Set([...(pre.warnings||[]),...(post.warnings||[])])];result={ok:true,bytes,summary:x,warnings};}catch(e){console.error(e);result={ok:false,errors:[e.message],warnings:[]};}finally{restoreParsedState(originalOuter,selectedId);}if(result.ok){$('validation').className='notice ok';$('validation').textContent=`PASS — 書出し前再解析OK / ${result.summary.entries}項目 / ${result.summary.characters}人 / ${result.summary.inventory}倉庫種${result.warnings.length?` / 警告 ${result.warnings.length}件`:''}`;toast('整合性PASS');}else{$('validation').className='notice error';$('validation').textContent='ERROR — '+result.errors.join(' / ');toast('整合性エラー：書き出しを停止します',4500);}renderCharacters();renderSummary();return result;}
async function exportZip(){try{const check=validate();if(!check.ok)throw Error('整合性検査に失敗したためZIPを書き出しません');const tmp2=check.bytes,inner=G2MD5(tmp2),first=G2MD5('222'+inner+'333'),second=S.originalTmp3.length===64?S.originalTmp3.slice(32):'00000000000000000000000000000000',tmp3=first+second,loc=S.location;const zip=new JSZip();for(const n of Object.keys(loc.zip.files)){if(n===loc.tmp2Name||n===loc.tmp3Name)continue;const f=loc.zip.file(n);if(f)zip.file(n,await f.async('uint8array'))}zip.file(loc.tmp2Name,tmp2);zip.file(loc.tmp3Name,tmp3);let result;if(loc.container==='nested'){const innerBytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE'}),outer=new JSZip();for(const n of Object.keys(loc.outerZip.files)){if(n===loc.innerName)continue;const f=loc.outerZip.file(n);if(f)outer.file(n,await f.async('uint8array'))}outer.file(loc.innerName,innerBytes);result=await outer.generateAsync({type:'blob',compression:'DEFLATE'});}else result=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const a=document.createElement('a');a.href=URL.createObjectURL(result);a.download=S.sourceName.replace(/\.zip$/i,'')+'_edited.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);S.dirty=false;$('dirtyStatus').textContent='書出し済み';$('saveMeta').textContent=`tmp3 ${first.slice(0,8)}… / ${tmp2.length.toLocaleString()} bytes`;toast('検証済みZIPを書き出しました');}catch(e){console.error(e);toast('書出し停止: '+e.message,5200)}}
function renderAll(){renderSummary();renderCharacters();renderItems();renderResources();renderEntries()}
$('openBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>e.target.files[0]&&openFile(e.target.files[0]);$('exportBtn').onclick=exportZip;$('cloneCharBtn').onclick=cloneSelectedCharacter;$('validateBtn').onclick=validate;$('itemSearch').oninput=renderItems;$('itemCategory').onchange=renderItems;$('entrySearch').oninput=renderEntries;$('addItemBtn').onclick=()=>{$('itemDialog').showModal();syncAddItemPreview()};$('confirmAddItem').onclick=e=>{e.preventDefault();try{addItem();$('itemDialog').close();}catch(err){toast('追加拒否: '+err.message,4800)}};['addBase','addTitle','addUltra'].forEach(id=>$(id).onchange=syncAddItemPreview);const drop=$('drop');drop.onclick=()=>$('fileInput').click();['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&openFile(e.dataTransfer.files[0]));tabs();loadDefinitions();
})();
