window.G2Model=(()=>{
const state={zip:null,tmp2:null,originalTmp3:'',outer:null,entries:new Map(),characters:[],inventory:[],dirty:false,sourceName:'',catalog:null};
const {KeyedArchive,isBplist}=G2Keyed;
function loadEntries(){state.entries.clear();const a=state.outer,o=a.raw(a.rootRef());if(!['NSDictionary','NSMutableDictionary'].includes(a.className(o)))throw Error('tmp2 rootが辞書ではありません');const ks=o['NS.keys']||[],vs=o['NS.objects']||[];for(let i=0;i<Math.min(ks.length,vs.length);i++){const key=a.decode(ks[i]),vi=a.uid(vs[i]);if(typeof key!=='string'||vi===null)continue;const vo=a.raw(vi);let data=vo&&vo['NS.data'];if(data instanceof BPList.UID)data=a.decode(data);if(isBplist(data)){try{state.entries.set(key,{key,dataObjectIndex:vi,archive:KeyedArchive.fromBytes(data)});}catch{}}}if(!state.entries.size)throw Error('内部セーブ項目を検出できません');}
function entry(k){const e=state.entries.get(k);if(!e)throw Error(`項目 ${k} がありません`);return e;}
function get(k){return entry(k).archive.decodeRoot();}
function setScalar(k,v){entry(k).archive.setRootValue(v);state.dirty=true;}
function loadCharacters(){state.characters=[];if(!state.entries.has('groups'))return;const ga=entry('groups').archive;const pages=ga.arrayRefs(ga.rootRef());for(let p=0;p<pages.length;p++){for(const [s,dr] of ga.arrayRefs(pages[p]).entries()){const di=ga.uid(dr);if(di===null)continue;const raw=ga.raw(di);let data=raw&&raw['NS.data'];if(data instanceof BPList.UID)data=ga.decode(data);if(!isBplist(data))continue;try{const ca=KeyedArchive.fromBytes(data);if(ca.className(ca.raw(ca.rootRef()))!=='Data_Character')continue;const d=ca.decodeRoot();state.characters.push({page:p,slot:s,parentDataIndex:di,archive:ca,data:d});}catch{}}}}
function syncCharacter(c){const ga=entry('groups').archive;ga.raw(c.parentDataIndex)['NS.data']=c.archive.toBytes();ga.dirty=true;state.dirty=true;c.data=c.archive.decodeRoot();}
function setCharacterField(c,key,v){c.archive.customSet(c.archive.rootRef(),key,v);syncCharacter(c);}
function specialCodes(c){const v=c.archive.customGet(c.archive.rootRef(),'_specialItems');return Array.isArray(v)?v.map(String):[];}
function setTraits(c,p1,p2){const keep=specialCodes(c).filter(code=>{const b=Number(String(code).slice(0,4));return !(b>=8807&&b<=8821)&&!(b>=8901&&b<=8918)});if(p1)keep.push(String(p1).padStart(4,'0')+'00030000');if(p2)keep.push(String(p2).padStart(4,'0')+'00030000');const raw=c.archive.raw(c.archive.rootRef()),ref=raw._specialItems;if(ref instanceof BPList.UID)c.archive.setArray(ref,keep);else c.archive.customSet(c.archive.rootRef(),'_specialItems',keep);syncCharacter(c);}
function loadInventory(){state.inventory=[];for(let cat=0;cat<=18;cat++){const k=`items${cat}`;if(!state.entries.has(k))continue;const a=entry(k).archive;let vals=a.decodeRoot();if(vals&&typeof vals==='object'&&!Array.isArray(vals))for(const [code,q] of Object.entries(vals))state.inventory.push({category:cat,code:String(code),quantity:Number(q),archive:a,key:k});}}
function setInventory(row,q){const a=row.archive;if(q<=0)a.dictDelete(a.rootRef(),row.code);else a.dictSet(a.rootRef(),row.code,Number(q));state.dirty=true;loadInventory();}
function addInventory(category,code,q=1){const k=`items${category}`;entry(k).archive.dictSet(entry(k).archive.rootRef(),String(code),Number(q));state.dirty=true;loadInventory();}
function flush(){for(const e of state.entries.values())if(e.archive.dirty){state.outer.raw(e.dataObjectIndex)['NS.data']=e.archive.toBytes();state.outer.dirty=true;}return state.outer.toBytes();}
function itemParts(code){const s=String(code).padStart(12,'0');return{base:s.slice(0,4),title:s.slice(4,8),ultra:s.slice(8,12)};}
function itemName(code){const p=itemParts(code),c=state.catalog||{};const base=c.items?.[p.base]?.name||`ID ${p.base}`;const t=c.normal_titles?.[p.title]||'';const u=c.ultra_titles?.[p.ultra]||'';return [u,t==='称号なし'?'':t,base].filter(Boolean).join(' ');}
function summary(){return{entries:state.entries.size,characters:state.characters.length,inventory:state.inventory.length,gp:state.entries.has('gp')?get('gp'):null,rabbit:state.entries.has('rabbit')?get('rabbit'):null};}
return{state,loadEntries,loadCharacters,loadInventory,entry,get,setScalar,setCharacterField,setTraits,setInventory,addInventory,flush,itemParts,itemName,summary,specialCodes};
})();
